FORMAT: 1A
HOST: https://jls-api.herokuapp.com/v1

# Jointly Logistics Service API

**Bem-vind(a)!**

API desenvolvida para prover o core do projeto JLS.

## Group Sobre a documentação
*Links com a documentação da API do projeto*

## Sobre [/]
> Informações gerais sobre construção, documentação e utilização desta API.

+ Response 200 (application/json)
    + Attributes (Documentation)

# Data Structures

## Documentation (object)

+ api: `JLS Jointly Logistics Service API` (string) - Nome da aplicação
+ docs: `https://github.com/thalysonalexr/jls-api#readme` (string) - Link para documentação principal
+ version: `v1` (string) - versão
